In [1]:
# 데이터 불러오는건 판다스 쓰고 처리하는건 모두 넘파이를 쓴다 
import numpy as np

In [2]:
data1 = [6,7.5,8,0,1]
data1

[6, 7.5, 8, 0, 1]

In [3]:
# numpy를 이용하여 1차원 배열로 변형하기 
arr1 = np.array(data1)
arr1
# numpy는 타입이 똑같아야 함, 숫자,문자 넣을수 없다. 어차피 머신러닝은 숫자여야함

array([6. , 7.5, 8. , 0. , 1. ])

In [4]:
# 배열의 크기 확인
arr1.shape # 1차원 (5,1)행렬
# numpy는 기본이 행렬이다 

(5,)

In [5]:
# 2차원 List
data2 = [
    [1,2,3,4],
    [5,6,7,8]
]

print(data2)

[[1, 2, 3, 4], [5, 6, 7, 8]]


In [6]:
# numpy로 2차원 배열로 변형하기
arr2 = np.array(data2)
arr2 # 2행 4열

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
# 행렬 차원 알기 , 자주 사용할것
arr2.shape # (행, 열)
# (2, 4) : 4차원 데이터 , 컬럼 = 차원

(2, 4)

In [12]:
# 0으로 구성된 1차원 배열 생성
print(np.zeros(5)) # 행

print(np.zeros([5,2])) # 행, 열 (2차원)

print(np.zeros([3, 5, 2])) # page(3차원) , 행 , 열

[0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [13]:
# 1로만 구성된 배열 생성 
# 0,1만 있다 나머지 숫자는 함수를 써야함
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
# 10
np.full(5,10) # 개수, 숫자

array([10, 10, 10, 10, 10])

In [15]:
np.zeros((3,5)) # 튜플, 리스트 아무거나 써도 됨

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones([3,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
# 숫자 8로 구성된 3행 5열 배열 생성 @ 자주 사용할 것
np.full([3,5], 8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [18]:
# 범위가 있는 배열 생성
np.arange(15)
# arrange아님@@@ a range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
arr1.dtype

dtype('float64')

In [21]:
arr3 = np.array([1,2,3,4,5] , dtype = np.int64)
arr3.dtype
arr3

array([1, 2, 3, 4, 5])

In [23]:
# data type을 변경
float_arr1 = arr3.astype(np.float64)
float_arr1.dtype

dtype('float64')

In [24]:
float_arr1

array([1., 2., 3., 4., 5.])

In [27]:
# 연산
arr1 = np.array([
    [1,2,3],
    [4,5,6]
])

# 튜플로 만들어도 됨 
# arr1 = np.array((
#     [1,2,3],
#     [4,5,6]
# ))

arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [31]:
arr1 = np.array([
    [1,2,3],
    [4,5,6]
], dtype= np.float64)
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [29]:
arr2 = np.array([
    [7,8,9],
    [10,11,12]
], dtype= np.float64)
arr2

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [32]:
# 더하기
arr1 + arr2 

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [34]:
# 뺄셈
arr1 - arr2 

array([[-6., -6., -6.],
       [-6., -6., -6.]])

In [35]:
#
arr1 / arr2

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [36]:
# 
arr1 * arr2

array([[ 7., 16., 27.],
       [40., 55., 72.]])

In [37]:

arr1*2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [38]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [41]:
arr3 = 1/ arr1
arr3

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [45]:
# epoch 이팍 (한국식 발음 에포크) ; 가중치 계산 오차 , 머신러닝에서 뺑뺑이 돌리는거
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr[5]
arr[5:9]
arr[5:9] = 12
arr
arr[:5]
arr[8:]

array([12,  9])

## 2차원 배열

In [50]:
arr2d = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
    ]
)
print(arr2d)
arr2d.dtype

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


dtype('int64')

In [58]:
np.arange(1,17).reshape(4,4) # 1~ 16을 4X4 배열로 만듦

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [56]:
# 자연어 처리 할때 이런 핸들링이 중요하다 
# 2번 행의 자료 출력
arr2d[2] # arr2d[2 , :] [행, 열]


array([ 9, 10, 11, 12])

In [60]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [66]:
# 1에서 2번 행의 자료 출력 
print(arr2d[1:3])

# 3번 열의 자료 출력
print(arr2d[:,3])

# 0,1열의 자료 출력
print(arr2d[:, :2])

# 1행 2열의 자료 출력
print(arr2d[1 , 2])

[[ 5  6  7  8]
 [ 9 10 11 12]]
[ 4  8 12 16]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
7


In [74]:
arr2d[:2,1:3] = np.zeros((2,2))
arr2d

array([[ 1,  0,  0,  4],
       [ 5,  0,  0,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

---
# 난수 발생
- rand : 0부터 1사이의 균일 분포
- randn : 가우시안 표준 정규 분포
- randint : 균일 분포의 정수 난수

## Boolean Indexing

In [100]:
names = np.array(['Charles' , 'Kenny' ,'Hayong' , "Charles" , "Hayong" , "Kenny" , "Kenny"])
data = np.random.randn(7 , 4) # 7행 4열
names

# <U7 은 무슨 타입? 
# unicode 7 character --- ASCII 코드 값 (7 bit ? )

# < Little Endian
# U Unicode
# 7 7 characters:

array(['Charles', 'Kenny', 'Hayong', 'Charles', 'Hayong', 'Kenny',
       'Kenny'], dtype='<U7')

In [101]:
names.shape

(7,)

In [102]:
print(data)
data.shape

[[ 0.35537683  0.38448014 -3.11778606 -0.21064831]
 [ 1.13666987 -0.79173798  0.85618571  0.73282977]
 [-1.32634133  0.20523647  1.37731311  0.05778219]
 [-0.32147229  2.7635084   0.93877438 -0.55238601]
 [-0.19535683  0.13751833  0.27697834 -1.71789662]
 [-1.14266223  1.44439967  0.0115343   1.52011148]
 [ 0.22064229 -1.50861234  1.97585166 -0.58149164]]


(7, 4)

In [103]:
# Mask를 이용한 추출
names == "Charles"

array([ True, False, False,  True, False, False, False])

In [104]:
data[names=="Charles" , :] # 0, 3번 행, True 값에 해당하는 행

array([[ 0.35537683,  0.38448014, -3.11778606, -0.21064831],
       [-0.32147229,  2.7635084 ,  0.93877438, -0.55238601]])

In [105]:
data[(names=="Charles") | (names=="Kenny") , :] 

array([[ 0.35537683,  0.38448014, -3.11778606, -0.21064831],
       [ 1.13666987, -0.79173798,  0.85618571,  0.73282977],
       [-0.32147229,  2.7635084 ,  0.93877438, -0.55238601],
       [-1.14266223,  1.44439967,  0.0115343 ,  1.52011148],
       [ 0.22064229, -1.50861234,  1.97585166, -0.58149164]])

In [106]:
data[:,3]

array([-0.21064831,  0.73282977,  0.05778219, -0.55238601, -1.71789662,
        1.52011148, -0.58149164])

In [107]:
data

array([[ 0.35537683,  0.38448014, -3.11778606, -0.21064831],
       [ 1.13666987, -0.79173798,  0.85618571,  0.73282977],
       [-1.32634133,  0.20523647,  1.37731311,  0.05778219],
       [-0.32147229,  2.7635084 ,  0.93877438, -0.55238601],
       [-0.19535683,  0.13751833,  0.27697834, -1.71789662],
       [-1.14266223,  1.44439967,  0.0115343 ,  1.52011148],
       [ 0.22064229, -1.50861234,  1.97585166, -0.58149164]])

In [108]:
# data의 4번째 열 값중 0보다 작은 것의 mask (조건) 만들기
data[data[:,3] < 0 , :]

array([[ 0.35537683,  0.38448014, -3.11778606, -0.21064831],
       [-0.32147229,  2.7635084 ,  0.93877438, -0.55238601],
       [-0.19535683,  0.13751833,  0.27697834, -1.71789662],
       [ 0.22064229, -1.50861234,  1.97585166, -0.58149164]])

In [109]:
# data 의 4번째 열의 값이 0보다 작은 data의 행을 0 으로 대체하기
data[data[ : , 3] < 0 , :] = 0
data

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.13666987, -0.79173798,  0.85618571,  0.73282977],
       [-1.32634133,  0.20523647,  1.37731311,  0.05778219],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [-1.14266223,  1.44439967,  0.0115343 ,  1.52011148],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [110]:
# 정렬
arr = np.random.rand(8)
arr

array([0.72026408, 0.86629622, 0.98970917, 0.04528342, 0.09018113,
       0.34638919, 0.29302295, 0.53944668])

In [111]:
# 오름차순 정렬
np.sort(arr)

array([0.04528342, 0.09018113, 0.29302295, 0.34638919, 0.53944668,
       0.72026408, 0.86629622, 0.98970917])

In [113]:
# 내림차순 정렬
np.sort(arr)[::-1] # 1차원일때

array([0.98970917, 0.86629622, 0.72026408, 0.53944668, 0.34638919,
       0.29302295, 0.09018113, 0.04528342])

In [114]:
# 2차원
arr = np.random.rand(5,3)
arr

array([[0.67317026, 0.10491422, 0.05015296],
       [0.66000193, 0.94820713, 0.63410966],
       [0.7847509 , 0.99647799, 0.38293482],
       [0.69484245, 0.15576284, 0.95429332],
       [0.70963278, 0.65374792, 0.7849495 ]])

In [116]:
# 오름차순 
print(np.sort(arr , axis = 0)) # 0 : 열방향 , 1 : 행방향
print(np.sort(arr , axis = 1)) # 0 : 열방향 , 1 : 행방향

[[0.66000193 0.10491422 0.05015296]
 [0.67317026 0.15576284 0.38293482]
 [0.69484245 0.65374792 0.63410966]
 [0.70963278 0.94820713 0.7849495 ]
 [0.7847509  0.99647799 0.95429332]]
[[0.05015296 0.10491422 0.67317026]
 [0.63410966 0.66000193 0.94820713]
 [0.38293482 0.7847509  0.99647799]
 [0.15576284 0.69484245 0.95429332]
 [0.65374792 0.70963278 0.7849495 ]]


In [120]:
# 내림차순
print(np.sort(arr , axis = 0)[::-1])
print(np.sort(arr , axis = 1)[:,::-1])

[[0.7847509  0.99647799 0.95429332]
 [0.70963278 0.94820713 0.7849495 ]
 [0.69484245 0.65374792 0.63410966]
 [0.67317026 0.15576284 0.38293482]
 [0.66000193 0.10491422 0.05015296]]
[[0.67317026 0.10491422 0.05015296]
 [0.94820713 0.66000193 0.63410966]
 [0.99647799 0.7847509  0.38293482]
 [0.95429332 0.69484245 0.15576284]
 [0.7849495  0.70963278 0.65374792]]


In [121]:
# 중복제거 
np.unique(names)

array(['Charles', 'Hayong', 'Kenny'], dtype='<U7')

---
# reshape ***중요

In [123]:
arr = np.arange(1,9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [125]:
arr.shape 
# 1차원 8개 행
# 행렬의 차원과 다른 차원 ?

(8,)

In [129]:
# 2차원 배열로 변경
arr.reshape(4,2)

arr1 = np.reshape(arr , (2,4))
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [131]:
# 3차원 배열로 변경 
arr2 = np.reshape(arr , (2, 2, 2)) # page, row , column
arr2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [135]:
# 2차원 배열을 1차원으로 변경
arr3 = arr1.reshape( -1 , 1) # 행의 갯수를 정할 수 없다. 알아서 정해라 : -1
arr3

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [143]:
# 3차원 배열을 1차원으로 변경 
# arr4 = arr2.reshape(-1 , 1 ,1) # 딥러닝에서는 1을 꼭 표시해줘야한다. (이미지 학습시킬 때) 1차원이라고 차원 수를 꼭 알려줘야한다
# arr4 = arr2.reshape(-1 , 1) 
arr4 = arr2.reshape(-1) # 일반적으로 사용 , 딥러닝에서는 사용하지 못함 
arr4

array([1, 2, 3, 4, 5, 6, 7, 8])

In [144]:
arr3 == arr4 # 단위 행렬 True 

array([[ True, False, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False],
       [False, False, False, False,  True, False, False, False],
       [False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False,  True]])

---