In [1]:
import pandas as pd
data = pd.read_csv("../Data/gpascore.csv")
data.head()

admit    gre   gpa  rank
0      0  380.0  3.21     3
1      1  660.0  3.67     3
2      1  800.0  4.00     1
3      1  640.0  3.19     4
4      0  520.0  2.33     4

admit : 합격여부 1 합격, 0 불합격       
gre : 영어 성적     
gpa : 학점      
rank : 지원한 대학원 수준       
// kaggle에 있다.

### Preprocessing (전처리)

In [2]:
# 결측치 처리
data.isnull().sum()

admit    0
gre      1
gpa      0
rank     0
dtype: int64

In [3]:
# 결측치 데이터 삭제
data.dropna(inplace= True)

# 결측치 데이터를 다른 값으로 대체하는 경우
# data.fillna(100)

In [4]:
# 처리 결과 확인
data.isnull().sum()

admit    0
gre      0
gpa      0
rank     0
dtype: int64

In [5]:
# rank의 종류 파악
sorted(data['rank'].unique())

[1, 2, 3, 4]

In [6]:
# 영어 점수의 최소값과 최대값
print('최대값 :' , data['gre'].max())
print('최소값 :' , data['gre'].min())

최대값 : 800.0
최소값 : 220.0


In [7]:
# Training Data
x = data[['gre' , 'gpa','rank']]
x.head()

gre   gpa  rank
0  380.0  3.21     3
1  660.0  3.67     3
2  800.0  4.00     1
3  640.0  3.19     4
4  520.0  2.33     4

In [8]:
# Target Data
y = data['admit']
y.head()

0    0
1    1
2    1
3    1
4    0
Name: admit, dtype: int64

In [9]:
# 갯수
data.describe()
x.count()

gre     425
gpa     425
rank    425
dtype: int64

---
### Deep Learning Model 만들기

In [10]:
from tensorflow import keras

옛날 방식이지만 중간 값을 보기에 좋은 방식이다

In [11]:
input_layer = keras.layers.InputLayer(input_shape = (3,))
hidden_layer = keras.layers.Dense(256, activation = "tanh")
output_layer = keras.layers.Dense(1, activation = "sigmoid")

In [12]:
model = keras.Sequential( # 인공신경망 도화지 만들기
    [
        input_layer,
        hidden_layer,
        output_layer
    ]
)

2022-07-20 10:53:59.726312: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [16]:
# model = keras.Sequential() # 인공신경망 도화지 만들기
# # 1번째 Hiddne Layer 만들기 : 256 노드 (보통 2의 배수로 사용, 임의의 갯수 (Hyper Parameter))
# # activation Function이 들어가야한다. activation = sigmoid , tanh(하이퍼탄젠트) , relu , softmax , leakyRelu
# model.add(keras.layers.Dense(256, activation = 'tanh', input_shape = (3,))) # 은닉층
# model.add(keras.layers.Dense(1, activation = 'sigmoid')) # 출력층

2022-07-19 17:36:42.693322: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [13]:
# 손실함수
# 들어 오는 값이 실수 이다
model.compile(optimizer = 'adam', loss='binary_crossentropy' , metrics = 'accuracy')
# 옴션 설명 --------------------------------
# optimizer : learning rate를 알맞게 조정해줌
# - adam 많이 사용, 점프해서 지나가면 다시 돌아오지 않음 
# - adagrad 아담에서 발전, 점프했다가 다시 돌아오기도 함
# - adadelta 
# - rmsprop
# - sgd

# loss 는 손실함수
# - binary_crossentropy : (이진분류) 분류 및 확률 예측

# metrics : 모댈의 평가 기준

In [21]:
# 학습 시키기
import numpy as np
# 딥러닝은 판다스 취급도 안함 넘파이로 변환해줘야 한다.
model.fit(np.array(x) , np.array(y) , epochs= 500 ) # verbose = 0 옵션 설정해주면 실행결과를 줄즐이 안보여준다 

Epoch 1/500
14/14 [==============================] - 0s 9ms/step - loss: 0.6738 - accuracy: 0.5482
Epoch 2/500
14/14 [==============================] - 0s 3ms/step - loss: 0.6622 - accuracy: 0.5765
Epoch 3/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6415 - accuracy: 0.6071
Epoch 4/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6355 - accuracy: 0.6282
Epoch 5/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6332 - accuracy: 0.6282
Epoch 6/500
14/14 [==============================] - 0s 3ms/step - loss: 0.6535 - accuracy: 0.6259
Epoch 7/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6365 - accuracy: 0.6188
Epoch 8/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6407 - accuracy: 0.6094
Epoch 9/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6498 - accuracy: 0.6212
Epoch 10/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6310 - accuracy: 0.6376
Epoch 11/

In [25]:
# hidden layer의 가중치 값 출력 
hidden_layer.get_weights()[0] # 256개씩 3개(input 갯수)
# 열이 3개(x1,x2,x3) 행이 256개

array([[-7.00915605e-02,  1.14002705e-01, -1.48860300e-02,
        -3.71126086e-02,  3.80892903e-02,  2.60059480e-02,
         7.64777511e-02, -3.73358019e-02, -1.25677688e-02,
        -1.50285289e-01, -1.32914364e-01, -8.77998918e-02,
         1.40389204e-01,  6.17040396e-02, -5.61542287e-02,
        -5.89340553e-02,  1.01996869e-01,  8.01922828e-02,
         3.26465582e-03,  3.90261114e-02, -1.42295673e-01,
        -1.07398666e-02,  1.49455488e-01, -2.69407630e-02,
        -5.09843901e-02,  6.68963045e-02,  9.48081613e-02,
         1.25994653e-01, -4.16638628e-02, -1.21492028e-01,
        -1.07636273e-01,  1.25394732e-01, -1.04919374e-01,
        -4.51972112e-02,  1.41450405e-01, -2.85153650e-02,
         6.11162037e-02,  8.46039206e-02, -2.18936708e-02,
         1.00280434e-01, -5.32170981e-02, -3.50785889e-02,
         1.51098728e-01,  3.51974927e-02,  4.82584536e-02,
         1.38937116e-01,  3.51573750e-02, -1.49236783e-01,
         8.08958411e-02, -3.55980806e-02,  1.47571350e-0

In [23]:
hidden_layer.get_weights()[1] # b 값

array([ 0.0000000e+00,  0.0000000e+00, -6.4614005e-02, -6.6299766e-04,
        0.0000000e+00,  1.9499810e-02,  0.0000000e+00, -2.3865589e-04,
       -1.6981599e-01,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00, -1.1359555e+00,  0.0000000e+00,
        0.0000000e+00,  5.6381607e-01,  0.0000000e+00, -2.2110257e-02,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00, -9.5953653e-03,
        0.0000000e+00,  0.0000000e+00, -3.2434188e-02,  0.0000000e+00,
        0.0000000e+00, -1.4219017e-05,  0.0000000e+00,  1.0238152e-02,
        0.0000000e+00,  0.0000000e+00,  6.1442994e-04,  0.0000000e+00,
        0.0000000e+00, -4.1050767e-03,  7.2079889e-02, -3.5004288e-02,
        0.0000000e+00,  0.0000000e+00, -1.0535098e-04,  0.0000000e+00,
      

In [22]:
# hidden layer의 출력 확인하기
intermediate_layer_model = keras.Model(inputs = model.input , outputs = model.layers[0].output)
intermediate_output = intermediate_layer_model(np.array(x))

In [20]:
intermediate_output
# 하이퍼 탄젠트 거친 값 ,  y^값 

<tf.Tensor: shape=(425, 256), dtype=float32, numpy=
array([[-1.        ,  1.        , -0.99904644, ...,  1.        ,
         1.        , -1.        ],
       [-1.        ,  1.        , -0.99999493, ...,  1.        ,
         1.        , -1.        ],
       [-1.        ,  1.        , -0.9999993 , ...,  1.        ,
         1.        , -1.        ],
       ...,
       [-1.        ,  1.        , -0.9998118 , ...,  1.        ,
         1.        , -1.        ],
       [-1.        ,  1.        , -0.9999989 , ...,  1.        ,
         1.        , -1.        ],
       [-1.        ,  1.        , -0.99999803, ...,  1.        ,
         1.        , -1.        ]], dtype=float32)>

---